# Generated by Django 3.2.7 on 2021-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImdbTutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
