# Generated by Django 3.2.7 on 2021-09-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImdbTutorial', '0002_auto_20210907_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='film',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
