# Generated by Django 3.2.7 on 2021-09-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appImdbTutorial', '0003_auto_20210907_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(2, 'Comedy'), (1, 'Horror'), (0, 'Else'), (3, 'Sci-fi'), (4, 'Drama')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appImdbTutorial.additionalinfo'),
        ),
    ]
