# Generated by Django 3.2.7 on 2021-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImdbTutorial', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (4, 'Drama'), (1, 'Horror'), (2, 'Comedy'), (0, 'Else')], default=0),
        ),
    ]
