# Generated by Django 3.2.7 on 2021-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImdbTutorial', '0006_alter_additionalinfo_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Else'), (2, 'Comedy'), (3, 'Sci-fi'), (1, 'Horror')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('movies', models.ManyToManyField(to='appImdbTutorial.Film')),
            ],
        ),
    ]
